### ISSUE TITLE
Some kld-cli commands not working on running node

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/lightning-knd#392]
```
[root@kld-00:~]# kld-cli help
Usage: kld-cli --target <TARGET> --cert-path <CERT_PATH> --macaroon-path <MACAROON_PATH> <COMMAND>

Commands:
  get-info          Fetch information about this lightning node
  sign              Creates a signature of the message using node's secret key (message limit 65536 chars)
  get-balance       Fetch confirmed and unconfirmed on-chain balance
  new-address       Generates new on-chain address for receiving funds
  withdraw          Send on-chain funds out of the wallet
  list-funds        Show available funds from the internal wallet
  list-peers        Fetch a list of this nodes peers
  connect-peer      Connect with a network peer
  disconnect-peer   Disconnect from a network peer
  list-channels     Fetch a list of this nodes open channels
  open-channel      Open a channel with another node
  set-channel-fee   Set channel fees
  close-channel     Close a channel
  network-nodes     Get node information from the network graph
  network-channels  Get channel information from the network graph
  fee-rates         Return feerate estimates, either satoshi-per-kw or satoshi-per-kb
  keysend           Pay a node without an invoice
  help              Print this message or the help of the given subcommand(s)

Options:
  -t, --target <TARGET>                IP address or hostname of the target machine
  -c, --cert-path <CERT_PATH>          Path to the TLS cert of the target API
  -m, --macaroon-path <MACAROON_PATH>  Path to the macaroon for authenticating with the API
  -h, --help                           Print help
  -V, --version                        Print version

[root@kld-00:~]# kld-cli get-info
Error executing command: error sending request for url (https://127.0.0.1:2244/v1/getinfo): connection closed before message completed

[root@kld-00:~]# kld-cli list-funds
Error executing command: error sending request for url (https://127.0.0.1:2244/v1/listFunds): connection closed before message completed

[root@kld-00:~]# kld-cli get-balance
{
  "totalBalance": xxxxx,
  "confBalance": xxxxx,
  "unconfBalance": 0
}

[root@kld-00:~]# kld-cli get-info
Error executing command: error sending request for url (https://127.0.0.1:2244/v1/getinfo): connection closed before message completed
```

`jounnalctl -u kld.service`

```
Jun 13 05:15:05 kld-00 kld-start[543921]: level=info pid=543921 message="Wallet is synchronised to blockchain" target="kld::wallet::bdk_wallet" node_id=one
Jun 13 05:15:39 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/channelmanager.rs:1932:61
Jun 13 05:15:45 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/channelmanager.rs:1932:61
Jun 13 05:15:55 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/channelmanager.rs:1932:61
Jun 13 05:16:30 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/peer_handler.rs:781:39
Jun 13 05:18:44 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/channelmanager.rs:1932:61
Jun 13 05:18:47 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/peer_handler.rs:781:39
Jun 13 05:18:56 kld-00 kld-start[543921]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/lightning-0.0.115/src/ln/channelmanager.rs:1932:61
```

**Comment by paulmattei** [comment]
Fixed in #391
